<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SpeckCartCookie\Module'                                  => __DIR__ . '/Module.php',
    'SpeckCartCookie\Mapper\CartCookieVerifierMapper'         => __DIR__ . '/src/SpeckCartCookie/Mapper/CartCookieVerifierMapper.php',
    'SpeckCartCookie\Mapper\CartVerifierMapperInterface'      => __DIR__ . '/src/SpeckCartCookie/Mapper/CartVerifierMapperInterface.php',
    'SpeckCartCookie\Service\CartCookie'                      => __DIR__ . '/src/SpeckCartCookie/Service/CartCookie.php',
    'SpeckCartCookieTest\Bootstrap'                           => __DIR__ . '/test/Bootstrap.php',
    'SpeckCartCookieTest\Mapper\CartCookieVerifierMapperTest' => __DIR__ . '/test/SpeckCartCookieTest/Mapper/CartCookieVerifierMapperTest.php',
    'SpeckCartCookieTest\Mapper\TestAsset\AbstractTestCase'   => __DIR__ . '/test/SpeckCartCookieTest/Mapper/TestAsset/AbstractTestCase.php',
    'SpeckCartCookieTest\Mapper\TestAsset\TestMapper'         => __DIR__ . '/test/SpeckCartCookieTest/Mapper/TestAsset/TestMapper.php',
    'SpeckCatalogTest\Service\CartCookieServiceTest'          => __DIR__ . '/test/SpeckCartCookieTest/Service/CartCookieServiceTest.php',
);
